# Generated by Django 4.2.7 on 2023-11-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brand name')),
                ('image', models.ImageField(upload_to='media/brands/', verbose_name='Brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProductCPU name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProductDisplay name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProductGPU name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProductMemory name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProductRam name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='main.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Product name')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('desc', models.TextField(verbose_name='product text')),
                ('audio', models.CharField(max_length=50, verbose_name='Audio name')),
                ('input_out', models.CharField(max_length=60, verbose_name='Input/Output')),
                ('camera', models.CharField(max_length=20, verbose_name='Camera')),
                ('usb_count', models.PositiveIntegerField(verbose_name='Usb count')),
                ('keboard_light', models.BooleanField(verbose_name='Keboard light')),
                ('brand', models.ManyToManyField(related_name='product_brand', to='main.brand')),
                ('cpu', models.ManyToManyField(related_name='cpu_code', to='main.productcpu')),
                ('display', models.ManyToManyField(related_name='display_code', to='main.productdisplay')),
                ('gpu', models.ManyToManyField(related_name='gpu_code', to='main.productgpu')),
                ('memory', models.ManyToManyField(related_name='memory_code', to='main.productmemory')),
                ('ram', models.ManyToManyField(related_name='ram_code', to='main.productram')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ManyToManyField(related_name='brand_subcategory', to='main.subcategory'),
        ),
    ]
