# Generated by Django 4.2.7 on 2023-11-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='media/products/', verbose_name='Product image'),
            preserve_default=False,
        ),
    ]
